dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gfortran

install:
  - pip3 install numpy scipy pytest pdoc3
  - pip3 install -e .

script:
  # generate the docs
  - mkdir -p docs
  - cd docs
  - pdoc3 --config latex_math=True --html -o . --force stripy
  - mv stripy/*.html .
  - rm -rf stripy/
  - cd ../

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  verbose: true
  local_dir: docs/
