{% set name = "stripy" %}
{% set version = "1.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 312d1ecefc8164f3b6bdf709408ed6ef794b786cdd524bc5d67f04037b0336c8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python
    - scipy >=0.15.0
  run:
    - numpy
    - python
    - scipy >=0.15.0



about:
  home: "https://github.com/underworldcode/stripy"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "Python interface to TRIPACK and STRIPACK fortran code for triangulation/interpolation in Cartesian coordinates and on a sphere"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
