name: API docs 

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.7

      - name: Install dependencies with conda
        shell: bash -l {0}
        run: |
          conda install pip 
          conda install -c conda-forge compilers numpy scipy 
          conda install pytest 
          conda install -c conda-forge pdoc3
          
      - name: Install stripy
        shell: bash -l {0}
        run: |
          pip install -e .
   
      - name: Build docs with pdoc
        shell: bash -l {0}
        run: |
          mkdir -p docs
          pdoc --config latex_math=True --html -o docs --force stripy

      # Here we can add an action to build the jupyter book to a different directory 
      # and then they can be uploaded together. The jupyter book can contain a link to the
      # API docs.

      # Note deploy key needs the ----BEGIN ... KEY---- lines too
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_PR_KEY }}
          publish_dir: docs/stripy