name: API docs 

on:
  push:
    branches: [master, dev]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Cache conda
        uses: actions/cache@v1
        env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/conda_pkgs_dir
            ~/.cache/pip
            # /usr/share/miniconda3/envs/jupyter-book
            # ~/GeodynamicsJupyterBook/GeodynamicsJupyterBook/_build
            
          key: ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/workflows/resources/conda_docs_environment.yml') }}

      - name: Miniconda + Cache
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniconda-version: "latest"
            environment-file: .github/workflows/resources/conda_docs_environment.yml
            activate-environment: conda-build-docs
            python-version: ${{ matrix.python-version }}
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

          
      - name: Build stripy
        shell: bash -l {0}
        run: |
          # conda update conda 
          conda-build conda
          echo "Conda Prefix = " ${CONDA_PREFIX}    

      - name: Install stripy from local build
        shell: bash -l {0}
        run: |
          # conda search stripy --use-local
          # conda install -c local stripy --use-local
          conda install -c ${CONDA_PREFIX} stripy
   
      - name: Build docs with pdoc
        shell: bash -l {0}
        run: |
          mkdir -p docs
          pdoc --config latex_math=True --html -o docs --force stripy

      # Here we can add an action to build the jupyter book to a different directory 
      # and then they can be uploaded together. The jupyter book can contain a link to the
      # API docs.

      # Note deploy key needs the ----BEGIN ... KEY---- lines too
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_PR_KEY }}
          publish_dir: docs/stripy