# This is a simple conda build which only succeeds when the built-in tests pass.

name: Conda Test Build 

on: 
  push
    
jobs:

  conda_build_test_deploy:
    name: Conda Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Conda build (no upload)
        shell: bash -l {0}
        run: |
            conda install --channel conda-forge conda-build conda-verify
            conda config --set anaconda_upload no
            conda-build --channel conda-forge  conda
