# This is a simple conda build which only succeeds when the built-in tests pass.

name: Conda Test Build 

on: 
  push
    
jobs:

  conda_build_test_deploy:
    name: Conda Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/conda_pkgs_dir
            # /usr/share/miniconda3/envs/jupyter-book
            # ~/.cache/pip
            # ~/GeodynamicsJupyterBook/GeodynamicsJupyterBook/_build
            
          key: ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/workflows/resources/conda_build_environment.yml') }}

      - name: Miniconda 
        uses: conda-incubator/setup-miniconda@v1
        with:
            miniconda-version: "latest"
            environment-file: .github/workflows/resources/conda_build_environment.yml
            activate-environment: conda-build
            python-version: ${{ matrix.python-version }}
            add_pip_as_python_dependency: False
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!


      # - uses: goanpeca/setup-miniconda@v1
      #   with:
      #     auto-update-conda: true
      #     python-version: ${{ matrix.python-version }}

      - name: Conda build (no upload)
        shell: bash -l {0}
        run: |
            conda config --set anaconda_upload no
            conda-build --channel conda-forge  conda
