name: Upload Python Package to PYPI (MacOS / wheel)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with: 
        python-version: ${{ matrix.python-version }}
    

    - name: Install miniconda 
      run: |
        wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-MacOSX-x86_64.sh -O ~/miniconda.sh 
        /bin/bash ~/miniconda.sh -b -p ~/myconda

    - name: Install dependencies 
      run: |
        source ~/myconda/etc/profile.d/conda.sh
        conda activate base
        python -m pip install --upgrade pip
        conda install -c conda-forge libgfortran
        conda install -c conda-forge pint
        conda install numpy scipy 
        conda install pytest
        
         
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        source ~/myconda/etc/profile.d/conda.sh
        conda activate base
        python setup.py bdist_wheel
        twine upload dist/*
