name: Python Build / Test with conda

on: [push]

jobs:
  build_and_test: 
    name: Build test (${{matrix.os}}, py ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]
        python-version: [ '3.7' ]

    steps:

      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies on 'ubuntu-latest' and 'windows-latest'       
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          conda install pip 
          conda install -c conda-forge fortran-compiler numpy scipy
          conda install pytest

      - name: Install dependencies on MacOS
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: |
          conda install pip 
          conda install -c conda-forge libgfortran=4.0.0 numpy scipy
          conda install pytest

          
      - name: Install (self)
        shell: bash -l {0}
        run: |
          python --version 
          pip install -e . 
          
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest


          