name: Python Build / Test on MACOS with conda

on: [push]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install miniconda 
      run: |
        wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-MacOSX-x86_64.sh -O ~/miniconda.sh 
        /bin/bash ~/miniconda.sh -b -p ~/myconda

    - name: Install dependencies 
      run: |
        source ~/myconda/etc/profile.d/conda.sh
        conda activate base
        python -m pip install --upgrade pip
        conda install -c conda-forge libgfortran
        conda install -c conda-forge pint
        conda install numpy scipy 
        conda install pytest
        
    - name: Install (self)
      run: |
        source ~/myconda/etc/profile.d/conda.sh
        conda activate base
        pip install -e . 
        # 
    - name: Test with pytest
      run: |
        source ~/myconda/etc/profile.d/conda.sh
        conda activate base
        pytest
