name: Python Build / Test with conda

on: [push]

jobs:
  build_and_test: 
    name: Build test (${{matrix.os}}, py ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]
        python-version: ['3.7', '2.7']

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Install dependencies 
        shell: bash -l {0}
        run: |
          conda install pip 
          conda install -c conda-forge fortran-compiler           
          conda install -c conda-forge pint
          conda install numpy scipy 
          conda install pytest
          
      - name: Install (self)
        shell: bash -l {0}
        run: |
          python --version 
          pip install -e . 
          
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest
