name: pip builds  

on: 
  push:
    branches:
      - master


jobs:
  build_with_pip:
    name: ${{matrix.os}} build with pip (${{ matrix.python-version }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest']
        python-version: ['2.7', '3.7', '3.8']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout  
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install gfortran (ubuntu)
        if: matrix.os == 'ubuntu-latest' 
        run: |
          sudo apt-get install -y gfortran

      - name: Install gfortran (macos)
        if: matrix.os == 'macos-latest' 
        run: |
          brew cask install gfortran
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy 
          pip install scipy 
          pip install Cython
          
      - name: Install (self)
        run: |
          pip install -e . 
          
      - name: Test with pytest
        run: |
          pip install pytest
          pytest


        