name: PYPI wheels macos

# on:
#   release:
#     types: [created]

on:
  push

jobs:
  deploy_to_pypi:
    name:  build and deploy manylinux on pypi 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    # - name: Install gfortran (ubuntu)
    #   if: matrix.os == 'ubuntu-latest' 
    #   run: |
    #     sudo apt-get install -y gfortran

    # - name: Install gfortran (macos)
    #   if: matrix.os == 'macos-latest' 
    #   run: |
    #     brew cask install gfortran

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        # pip install numpy
        # pip install scipy
        # pip install Cython


    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38m'
        build-requirements: 'cython numpy scipy'
        system-packages: 'libgfortran'
        package-path: ''
        pip-wheel-args: '--no-deps'
        
    - name: Build the wheel
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
 
      run: |
        twine upload wheelhouse/*-manylinux*.whl --skip-existing